prostageAccueil:
    path: /
    controller: App\Controller\ProstageController::index

prostageEntreprises:
    path: /entreprises
    controller: App\Controller\ProstageController::entreprises

prostageEntreprise:
    path: /entreprises/{id}
    controller: App\Controller\ProstageController::entreprise

prostageFormations:
    path: /formations
    controller: App\Controller\ProstageController::formations

prostageFormation:
    path: /formations/{id}
    controller: App\Controller\ProstageController::formation

prostageStages:
    path: /stages/{id}
    controller: App\Controller\ProstageController::stage

prostageAjoutEntreprise:
    path: admin/entreprise/new
    controller: App\Controller\ProstageController::ajoutEntreprise

prostageMoficationEntreprise:
    path: admin/entreprise/update/{id}
    controller: App\Controller\ProstageController::modificationEntreprise

prostageAjoutStage:
    path: user/stage/new
    controller: App\Controller\ProstageController::ajoutStage