prostageAccueil:
    path: /
    controller: App\Controller\ProstageController::index

prostageEntreprises:
    path: /entreprises
    controller: App\Controller\ProstageController::entreprises

prostageFormations:
    path: /formations
    controller: App\Controller\ProstageController::formations

prostageStages:
    path: /stages/{id}
    controller: App\Controller\ProstageController::stages